/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './view/routes/__root'
import { Route as IndexRouteImport } from './view/routes/index'

const TestsStyleLazyRouteImport = createFileRoute('/tests/style')()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsStyleLazyRoute = TestsStyleLazyRouteImport.update({
  id: '/tests/style',
  path: '/tests/style',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./view/routes/tests/style.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tests/style': typeof TestsStyleLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tests/style': typeof TestsStyleLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tests/style': typeof TestsStyleLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tests/style'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tests/style'
  id: '__root__' | '/' | '/tests/style'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestsStyleLazyRoute: typeof TestsStyleLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/style': {
      id: '/tests/style'
      path: '/tests/style'
      fullPath: '/tests/style'
      preLoaderRoute: typeof TestsStyleLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestsStyleLazyRoute: TestsStyleLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
